config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("list/", views.ReservationListView.as_view(), name="list"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.CreatePhotoView.as_view(), name="add-photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.DeletePhotoView.as_view(),
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path(
        "verify/<str:secret>/",
        views.complete_verification,
        name="complete-verification",
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path(
        "update-Password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch_language/", views.switch_language, name="switch_language"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-20 border-t font-semibold text-gray-600">
    <div class="flex flex-col">
        <span>
           {% trans "Please don't copy me." %}
        </span>
        <span>
           &copy; Bongnb, Inc. {% trans "All rights reserved." %}
        </span>
    </div>
    <div class="mt-10">
        {% get_current_language as LANGUAGE_CODE %}
        <select id="js-lang" class="w-40 p-1">
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %} selected {% endif %}>한국어</option>
            <option value="en" {% if LANGUAGE_CODE == 'en' %} selected {% endif %}>English</option>
        </select>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute mx-auto left-0 right-0 top-0 flex justify-center">
        {% for message in messages %}
            <li class="message font-medium rounded-full text-white py-4 px-10 shadow-md z-10 {% if message.tags %}{{message.tags}}{% endif %}">{{message}}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-bold h-full">
    {% if user.is_authenticated %}
        <li class="nav-link">
            <a href="{% url 'users:switch-hosting' %}">
                {% if request.session.is_hosting %}
                    일반 모드로 전환
                {% else %}
                    관리자 모드로 전환
                {% endif %}
            </a>
        </li>
        {% if request.session.is_hosting %}
            <li class="nav-link"><a href="{% url 'rooms:create' %}">숙소 추가</a></li>
        {% endif %}
        <li class="nav-link"><a href="{% url 'reservations:list' %}">예약 목록</a></li>
        <li class="nav-link"><a href="{% url "lists:see-favs" %}">저장 목록</a></li>
        <li class="nav-link"><a href="{{user.get_absolute_url}}">프로필</a></li>
        <li class="nav-link"><a href="{% url "users:logout" %}">로그아웃</a></li>
    {% else %}
        <li class="nav-link"><a href="{% url "users:signup" %}">회원 가입</a></li>
        <li class="nav-link"><a href="{% url "users:login" %}">로그인</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn border-2 border-gray-700 text-black mb-2">
        <i class="fab fa-github-alt fa-lg mr-2"></i>Github로 시작하기
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn border border-yellow-500 text-black bg-yellow-500">
        <i class="fas fa-comment fa-lg mr-2"></i>kakao로 시작하기
    </a>
</div>
<div class="flex items-center w-full">
    <div class="h-px w-full bg-gray-500"></div>
    <span class="text-gray-700 font-bold py-8 px-4">or</span>
    <div class="h-px w-full bg-gray-500"></div>
</div>