config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.CreatePhotoView.as_view(), name="add-photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.DeletePhotoView.as_view(),
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/mixins/room_card.html
{% load on_favs %}
<div class="w-full sm:w-1/2 lg:w-1/4 mb-10 px-4 sm:px-2 relative">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 rounded-lg mb-2 overflow-hidden">
            <div class="w-full h-full bg-cover bg-center transform hover:scale-110 duration-150 ease-in-out" style="background-image: url({{room.get_first_photo}});"></div>
        </div>
        <div class="flex justify-between mb-2">
            <div class="flex w-10/12">
                {% if room.host.superhost %}
                    <span class="uppercase text-black font-semibold text-xs border border-black rounded py-px px-1 mr-2">superhost</span>
                {% endif %}
                <span class="text-sm text-gray-600 block truncate">{{room.city}}, {{room.country.name}}</span>
            </div>
            
            {% if room.get_total_rating != 0 %}
                <span class="text-sm flex items-center">
                    <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{room.get_total_rating}}
                </span>
            {% endif %}
                
        </div>
        <span class="text-black w-11/12 block truncate">{{room.name}}</span>
    </a>
    
    {% on_favs room as on_favs_boolean %}
    
    {% if on_favs_boolean %}
        <a
            href="{% url 'lists:toggle-room' room.pk %}?action=remove"
            class="absolute top-0 right-0 bg-white opacity-75 h-8 w-8 mr-4 mt-2 rounded flex items-center justify-center text-red-500
            transition duration-150 hover:opacity-100 hover:shadow-md ease-in-out
        "><i class="text-base fas fa-heart"></i>
        </a>
    {% else %}
        <a href="{% url 'lists:toggle-room' room.pk %}?action=add"
            class="absolute top-0 right-0 bg-white opacity-75 h-8 w-8 mr-4 mt-2 rounded flex items-center justify-center
            transition duration-150 hover:opacity-100 hover:shadow-md hover:text-red-500 ease-in-out
        "><i class="text-base far fa-heart"></i>
        </a>
    {% endif %}

    </a>
</div>

templates/mixins/room_reservation.html
<div class="w-full sm:w-1/2 lg:w-1/3 xl:w-1/4 mb-10 px-4 sm:px-2">

    <div class="font-medium mb-1">
        <span>
            {{reservation.check_in|date:"Y년 n월 d일"}}
        </span>
        <span>-</span>
        <span>
            {{reservation.check_out|date:"Y년 n월 d일"}}
        </span>
    </div>

    <span class="inline-block py-px px-1 mb-1 border rounded font-semibold text-xs capitalize
        {% if reservation.status == 'pending' %}
            text-orange-500 border-orange-500
        {% elif reservation.status == 'confirmed' %}
            text-blue-600 border-blue-600
        {% elif reservation.status == 'canceled' %}
            text-red-600 border-red-600
        {% endif %}
    ">
        {{reservation.status}}
    </span>

    <a href="{% url 'reservations:detail' reservation.pk %}">

        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2 overflow-hidden">
            <div class="w-full h-full bg-cover bg-center transform hover:scale-110 duration-150 ease-in-out" style="background-image: url({{reservation.room.get_first_photo}});">

            </div>
        </div>

        <div class="flex justify-between mb-2">
            <div class="flex w-10/12">
                {% if reservation.room.host.superhost %}
                    <span class="uppercase text-black font-semibold text-xs border border-black rounded py-px px-1 mr-2">superhost</span>
                {% endif %}
                <span class="text-sm text-gray-600 block truncate">{{reservation.room.city}}, {{reservation.room.country.name}}</span>
            </div>
            
            {% if reservation.room.get_total_rating != 0 %}
                <span class="text-sm flex items-center">
                    <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{reservation.room.get_total_rating}}
                </span>
            {% endif %}
                
        </div>
        <span class="text-black w-11/12 block truncate">{{reservation.room.name}}</span>
    </a>
</div>

templates/mixins/room_search.html
<div class="w-full mb-10">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url({{room.get_first_photo}});">
        </div>
        <div class="flex justify-between items-center mb-2">
            <div class="flex items-center">
                {% if room.host.superhost %}
                    <span class="uppercase text-black font-semibold text-xs border border-black rounded py-px px-1 mr-2">superhost</span>
                {% endif %}
                <span class="text-sm text-gray-600 block truncate">{{room.room_type}}</span>
            </div>
            
            {% if room.get_total_rating != 0 %}
                <span class="text-sm flex items-center">
                    <i class="fas fa-star text-red-500 text-xs mr-1"></i>{{room.get_total_rating}}
                </span>
            {% endif %}
                
        </div>
        <div class="font-semibold truncate mb-1">{{room.name}}</div>
        <div class="text-gray-700 text-sm mb-1">
            인원 {{room.guests}}명 · 침실 {{room.bedrooms}}개 · 침대 {{room.beds}}개 · 욕실 {{room.baths}}개
        </div>
        <div class="text-gray-700 text-sm">
            {% for amenity in room.get_four_amenities %}
                <span>{{amenity}}</span>
                {% if not forloop.last %}<span>|</span>{% endif %}
            {% endfor %}
        </div>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
    <div class="{{h_and_w|default:'h-20 w-20'}} bg-blue-900 rounded-full bg-cover" style="background-image: url({{user.avatar.url}});">
{% else %}
    <div class="{{h_and_w|default:'h-20 w-20'}} bg-blue-900 rounded-full flex justify-center items-center">
        <span class="{{text_size|default:'text-3xl'}} text-white font-medium">{{user.first_name|first}}</span>
{% endif %}
    </div>