config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.CreatePhotoView.as_view(), name="add-photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.DeletePhotoView.as_view(),
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models
from cal import Calendar
import random


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Model Definition """

    description = models.TextField(null=True)

    class Meta:
        verbose_name = "Room Type"
        ordering = ["name"]


class Amenity(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Model Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

    def get_absolute_url(self):
        return reverse("rooms:photos", kwargs={"pk": self.room.pk})


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(help_text="How many people will be staying?")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    # To know - on_delete(CASCADE): 부모가 삭제되면, 자식도 삭제됨(일대다관계)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField(Amenity, related_name="rooms", blank=True)
    facilities = models.ManyToManyField(Facility, related_name="rooms", blank=True)
    house_rule = models.ManyToManyField(HouseRule, related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def get_total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def get_first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            # ↓ Todo: default 이미지 url 넣기
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        photos_url = []
        if photos.exists():
            for photo in photos:
                photos_url.append(photo.file.url)
            return photos_url
        else:
            # ↓ Todo: default 이미지 url 넣기
            return [None, None, None, None]

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        next_year = this_year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            next_year = this_year + 1
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(next_year, next_month)
        return [this_month_cal, next_month_cal]

    def get_four_amenities(self):
        amenities = list(self.amenities.all())
        # random.shuffle(amenities)
        random.shuffle(amenities)
        return amenities[:4]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere", required=False)
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        empty_label="전체", queryset=models.RoomType.objects.all(), required=False
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    # amenities = forms.ModelMultipleChoiceField(
    #     required=False,
    #     queryset=models.Amenity.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    # )
    # facilities = forms.ModelMultipleChoiceField(
    #     required=False,
    #     queryset=models.Facility.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    # )


class CreatePhotoForm(forms.ModelForm):
    """ 숙소 사진 추가 Form """

    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    """ 숙소 추가 Form """

    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rule",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.db.models import Q
from django.views.generic import (
    ListView,
    View,
    DetailView,
    UpdateView,
    FormView,
    DeleteView,
)
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as User_mixins
from . import models, forms


class HomeView(ListView):

    """ HomeView Definition"""

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "-created"
    context_object_name = "rooms"


class RoomDetail(DetailView):

    """ RoomDetail Definition """

    model = models.Room


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():
                # print(request.GET)
                # url에 있는 data
                # print(form)
                # url에 있는 data를 이용하여 form html을 만듬
                # print(form.cleaned_data)
                # forms.py를 참고해서 form html에 담겨있는 필요한 정보만 가져옴 & 정제(ex, str > int)
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                # amenities = form.cleaned_data.get("amenities")
                # facilities = form.cleaned_data.get("facilities")

                """ filter """
                filter_args = Q()

                if city != "Anywhere":
                    filter_args &= Q(city__startswith=city)

                filter_args &= Q(country=country)

                if room_type is not None:
                    filter_args &= Q(room_type=room_type)

                if price is not None:
                    filter_args &= Q(price__lte=price)

                if guests is not None:
                    filter_args &= Q(guests__gte=guests)

                if bedrooms is not None:
                    filter_args &= Q(bedrooms__gte=bedrooms)

                if beds is not None:
                    filter_args &= Q(beds__gte=beds)

                if baths is not None:
                    filter_args &= Q(baths__gte=baths)

                if instant_book is True:
                    filter_args &= Q(instant_book=True)

                if superhost is True:
                    filter_args &= Q(host__superhost=True)

                qs = models.Room.objects.filter(filter_args)

                # for amenity in amenities:
                # rooms = rooms & models.Room.objects.filter(amenities=amenity)
                # qs = qs.filter(amenities=amenity)

                # for facility in facilities:
                # rooms = rooms & models.Room.objects.filter(facilities=facility)
                # qs = qs.filter(facilities=facility)

                qs = qs.order_by("-created")

                paginator = Paginator(qs, 10)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                """ query_string 만들기_Pagination """

                urlencode = request.GET.urlencode()

                query_list = [i for i in urlencode.split("&") if "page=" not in i]
                """
                복잡한 버전
                query_list = []
                for i in urlencode.split("&"):
                    if "page=" not in i:
                        query_list.append(i)
                """

                query_string = "&".join(query_list)

                return render(
                    request,
                    "rooms/room_search.html",
                    {"form": form, "rooms": rooms, "query_string": query_string},
                )

        else:
            form = forms.SearchForm()

        return render(request, "rooms/room_search.html", {"form": form})


class EditRoomView(User_mixins.LoggedInOnlyView, UpdateView):
    """ 숙소를 수정하기 위한 View """

    model = models.Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rule",
    )
    template_name = "rooms/room_edit.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(User_mixins.LoggedInOnlyView, DetailView):
    """ 숙소 사진 목록 View """

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class CreatePhotoView(User_mixins.LoggedInOnlyView, UserPassesTestMixin, FormView):
    """ 숙소 사진 생성 View """

    template_name = "rooms/photo_create.html"
    form_class = forms.CreatePhotoForm

    def test_func(self):
        room_pk = self.kwargs.get("pk")
        room = models.Room.objects.get(pk=room_pk)
        return room.host.pk == self.request.user.pk

    def handle_no_permission(self):
        messages.error(self.request, "⛔ 권한이 없는 페이지입니다.")
        return redirect(reverse("core:home"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # room_pk = self.kwargs.get("pk")
        context["room_pk"] = self.kwargs.get("pk")
        return context

    def form_valid(self, form):
        # form은 kwargs를 모르기에 view에서 form에 전달해줌
        room_pk = self.kwargs.get("pk")
        form.save(room_pk)
        messages.success(self.request, "뀨! 사진이 업로드되었습니다.")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))


class DeletePhotoView(User_mixins.LoggedInOnlyView, SuccessMessageMixin, DeleteView):
    """ 숙소 사진 삭제 View """

    model = models.Photo
    pk_url_kwarg = "photo_pk"
    template_name = "rooms/photo_delete.html"

    def get_object(self, queryset=None):
        photo = super().get_object(queryset=queryset)
        if photo.room.host.pk != self.request.user.pk:
            raise Http404()
        return photo

    def delete(self, request, *args, **kwargs):
        user = self.request.user
        room_pk = self.kwargs.get("room_pk")
        try:
            room = models.Room.objects.get(pk=room_pk)
            if room.host.pk != user.pk:
                messages.error(self.request, "⛔ 사진을 삭제할 수 없습니다.")
                return redirect(reverse("core:home"))
        except models.Room.DoesNotExist:
            messages.error(self.request, "존재하지 않는 숙소입니다.")
            return redirect(reverse("core:home"))
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        messages.success(self.request, "✔ 사진을 삭제했습니다.")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class EditPhotoView(User_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    """ 숙소 사진 수정 View """

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption",)
    success_message = "✔ 사진을 수정했습니다."

    def get_object(self, queryset=None):
        photo = super().get_object(queryset=queryset)
        if photo.room.host.pk != self.request.user.pk:
            raise Http404()
        return photo

    # Model.Photo에서 get_absolute_url을 통해 같은 방식을 취할 수 있음
    # def get_success_url(self):
    #     room_pk = self.kwargs.get("room_pk")
    #     return reverse("room:photos", kwargs={'pk': room_pk})


class CreateRoomView(User_mixins.LoggedInOnlyView, UserPassesTestMixin, FormView):
    """ 숙소 추가 View """

    template_name = "rooms/room_create.html"
    form_class = forms.CreateRoomForm

    def test_func(self):
        try:
            is_hosting = self.request.session["is_hosting"]
            return is_hosting
        except KeyError:
            return False

    def handle_no_permission(self):
        messages.error(self.request, "⛔ 관리자 모드일 때 접근 가능한 페이지입니다.")
        return redirect(reverse("core:home"))

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        # ↑ 새로 만든 숙소는 db에 저장됨
        form.save_m2m()
        messages.success(self.request, "숙소가 업로드 되었습니다.")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/detail.html
{% extends "base.html" %}

{% block page_name %}
    home
{% endblock page_name %}

{% block content %}
    <div>
        <h1>{{room.name}}</h1>
        <h3>{{room.description}}</h3>
    </div>
    <div>
        <h2>
            By: {{room.host.username}}
            {% if room.host.superhost %}
                (superhost)
            {% endif %}
        </h2>
        <h3>Amenities</h3>
        <ul>
            {% for a in room.amenities.all %}
                <li>{{a}}</li>
            {% endfor %}
        </ul>
        <h3>Facilities</h3>
        <ul>
            {% for f in room.facilities.all %}
                <li>{{f}}</li>
            {% endfor %}
        </ul>
        <h3>House Rules</h3>
        <ul>
            {% for h in room.house_rule.all %}
                <li>{{h}}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
    사진 업로드
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container mx-auto mt-32 mb-10 flex flex-col">

        <div class="p-4 mb-4 border-b border-gray-300">
          <a href="{% url 'rooms:photos' pk=room_pk %}" class="text-blue-500 font-medium">
              <i class="fas fa-arrow-left"></i>
              <span>사진 목록</span>
          </a>
        </div>
        
        <div class="mx-auto py-10 px-6 mb-10 items-center border border-gray-300 md:w-1/2 lg:w-5/12 xl:w-4/12">

            {% include "mixins/room/room_form.html" with form=form cta="사진 업로드" %}
    
        </div>

    </div>

{% endblock content %}

templates/rooms/photo_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
    사진 수정
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container mx-auto mt-32 mb-10 flex flex-col">

        <div class="p-4 mb-4 border-b border-gray-300">
          <a href="{{photo.get_absolute_url}}" class="text-blue-500 font-medium">
              <i class="fas fa-arrow-left"></i>
              <span>사진 목록</span>
          </a>
        </div>
        
        <div class="mx-auto py-10 px-6 mb-10 items-center border border-gray-300 md:w-1/2 lg:w-5/12 xl:w-4/12">
            
            {% include "mixins/room/room_form.html" with form=form cta="사진 수정" %}
    
        </div>

    </div>

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load is_booked on_favs %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
    <div class="container max-w-full mb-20 flex h-50vh lg:h-75vh">
        <div class="h-full w-full sm:w-1/2 border border-gray-500 overflow-hidden">
            <div class="w-full h-full bg-cover bg-center transform hover:scale-110 duration-300 ease-in-out" style="background-image: url({{room.get_first_photo}})"></div>
        </div>
        <div class="h-full w-0 sm:w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div class="h-auto w-1/2 border border-gray-500 overflow-hidden">
                    <div class="w-full h-full bg-cover bg-center transform hover:scale-110 duration-300 ease-in-out" style="background-image: url({{photo}})"></div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-8/12">
            {% on_favs room as on_favs_boolean %}
            <div class="flex justify-between mb-4">
                <div class="mr-6">
                    <h4 class="text-2xl font-medium">{{room.name}}</h4>
                    <span class="text-gray-700 font-light block mb-4">{{room.city}}</span>
                    {% if on_favs_boolean %}
                        <a href="{% url 'lists:toggle-room' room.pk %}?action=remove" class="text-lg font-medium"><i class="text-base fas fa-heart text-red-500 mr-2"></i>저장됨</a>
                    {% else %}
                        <a href="{% url 'lists:toggle-room' room.pk %}?action=add" class="text-lg font-medium"><i class="text-base far fa-heart mr-2"></i>저장</a>
                    {% endif %}
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=room.host %}
                    <span class="mt-1 font-medium text-gray-500">{{room.host.first_name}}</span>
                </a>
            </div>
            
                
            <div class="flex border-section">
                <span class="mr-6">인원 {{room.guests}}명</span>
                <span class="mr-6">침대 {{room.beds}}개</span>
                <span class="mr-6">침실 {{room.bedrooms}}개</span>
                <span class="mr-6">욕실 {{room.baths}}개</span>
            </div>
            <div class="border-section">
                <span class="">{{room.room_type}}</span>
            </div>
            <p class="border-section">{{room.description}}</p>
            <div class="border-section">
                <h4 class="font-semibold text-lg mb-4">편의시설</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %}
            </div>
            <div class="my-6">
                <h4 class="font-semibold text-2xl mb-4">후기</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-500"></i>
                        <span class="font-semibold text-lg">{{room.get_total_rating}}</span>
                    </div>
                    <div class="mx-4 w-px h-5 bg-gray-500"></div>
                    <div>
                        <span class="font-semibold text-lg mr-1">{{room.reviews.count}}</span>
                        <span class="font-medium text-lg">후기</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-2 flex">
                                <div class="mr-2">
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w='h-12 w-12' text_size='text-xl' %}
                                </div>
                                <div class="flex flex-col">
                                    <span class="font-semibold">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-700">{{review.created|date:"Y"}}년 {{review.created|date:"m"}}월</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="border-section">
                <h4 class="font-semibold text-lg mb-4">시설</h4>
                {% for f in room.facilities.all %}
                    <li class="mb-2">{{f}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-semibold text-lg mb-4">숙소 이용규칙</h4>
                {% for r in room.house_rule.all %}
                    <li class="mb-2">{{r}}</li>
                {% endfor %}
            </div>
        </div>
        <div class="w-3/12">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">숙소 수정</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars %}
                        <div class="mb-20">
                            <span class="text-center font-semibold text-lg block mb-5">{{calendar.get_month}}/{{calendar.year}}</span>
                            <div class="grid mb-2 grid-cols-7 gap-2">
                                {% for day in calendar.day_names %}
                                    <span class="text-center font-semibold">{{day}}</span>
                                {% endfor %}
                            </div>
                            <div class="grid mb-4 grid-cols-7 gap-2">
                                {% for day in calendar.get_days %}
                                    {% is_booked room day as is_booked_bool %}
                                    {% if day.number != 0 %}
                                        {% if day.is_past %}
                                            <span class="text-center bg-gray-300 rounded-md p-1 text-gray-500 cursor-default">{{day}}</span>
                                        {% elif is_booked_bool %}
                                            <span class="text-center bg-gray-300 rounded-md p-1 text-gray-500 line-through cursor-default">{{day}}</span>
                                        {% else %}
                                            <a href="{% url 'reservations:create' room=room.pk year=day.year month=day.month day=day.number %}" class="text-center bg-gray-300 rounded-md p-1 cursor-pointer hover:bg-teal-400 hover:text-white hover:font-semibold">{{day}}</a>
                                        {% endif %}
                                    {% else %}
                                        <span></span>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
  {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
  <div class="container mx-auto mt-32 mb-10 flex flex-col">
    <div class="p-4 mb-4 border-b border-gray-300 flex justify-between items-center">
      <a href="{% url 'rooms:edit' pk=room.pk %}" class="text-blue-500 font-medium">
        <i class="fas fa-arrow-left"></i>
        <span>숙소 수정</span>
      </a>
      <a href="{% url 'rooms:add-photos' room.pk %}" class="font-medium text-base btn-link w-40">
        <i class="fas fa-image"></i>
        <span>사진 업로드</span>
      </a>
    </div>
    {% for photo in room.photos.all %}
      <div class="mb-4 py-6 px-4 border border-gray-300 flex justify-between">
        <div class="flex items-start w-full">
          <div class="w-32 h-32 mr-4 bg-cover bg-center" style="background-image: url({{photo.file.url}});"></div>
          <span class="text-lg">{{photo.caption}}</span>
        </div>
        <div class="flex flex-col w-32 justify-center">
          <a href="{% url 'rooms:edit-photo' room_pk=room.pk photo_pk=photo.pk %}" class="btn-link mb-4 text-base bg-blue-400">수정</a>
          <a href="{% url 'rooms:delete-photo' room_pk=room.pk photo_pk=photo.pk %}" class="btn-link text-base bg-red-400">삭제</a>
        </div>
      </div>
    {% endfor %}

  </div>

{% endblock content %}

templates/rooms/room_search.html
{% extends "base.html" %}

{% block page_title %}
  Search
{% endblock page_title %}

{% block content %}

  <div class="min-h-75vh container container-m-p">
    

    <div class="flex flex-col md:flex-row">
      <div class="w-full md:w-1/3 md:border-r md:pr-4">
        <p class="text-lg font-semibold mb-6">검색</p>
        <form method="get" action="{% url 'rooms:search' %}"
        class=""
        >
          {{form.as_p}}
          <button class="btn text-base bg-indigo-500 text-white mt-10">Search</button>
        </form>
      </div>
  
      <div class="w-full mt-20 md:mt-0 md:w-2/3 md:ml-4">
        <p class="text-lg font-semibold mb-6">검색 결과</p>
        <div class="">
          {% for room in rooms %}
            {% include "mixins/room_search.html" with room=room %}
          {% endfor %}
        </div>
  
        <div class="flex flex-col items-center mb-10">
          <div class="">
            {% if rooms.has_previous %}
              <a href="?{{query_string}}&page={{rooms.previous_page_number}}">
                <i class="fas fa-arrow-left"></i>
              </a>
            {% endif %}
            
            {% if rooms %}
              <span class="font-medium">
                Page {{rooms.number}} of {{rooms.paginator.num_pages}}
              </span>
            {% endif %}

            {% if rooms.has_next %}
              <a href="?{{query_string}}&page={{rooms.next_page_number}}">
                <i class="fas fa-arrow-right"></i>
              </a>        
            {% endif %}
          </div>
          
          <div class="flex">
            {% for page in rooms.paginator.page_range %}
              <a class="font-medium
                {% if not forloop.last %}
                  mr-1
                {% endif %}
                " href="?{{query_string}}&page={{page}}"
              >{{page}}</a>
            {% endfor %}
          </div>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}