config/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path(os.environ.get("DJANGO_ADMIN_URL", "admin/"), admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
    path("list/", views.ReservationListView.as_view(), name="list"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models


class BookedDay(core_models.TimeStampedModel):
    """ BookedDay Model Definition """

    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return f"{self.day}_{self.reservation.room.name}"


class Reservation(core_models.TimeStampedModel):

    """ Reservation Model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", related_name="reservations", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="reservations", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            check_in = self.check_in
            check_out = self.check_out
            period = check_out - check_in
            is_booked = BookedDay.objects.filter(
                day__range=(check_in, check_out), reservation__room=self.room
            ).exists()
            if not is_booked:
                super().save(*args, **kwargs)
                # ↓ 시작을 포함하는 경우에는 1을 더해준다
                for i in range(period.days + 1):
                    day = check_in + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        else:
            return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View, ListView
from django.contrib import messages
from django.shortcuts import redirect, reverse, render
from rooms import models as room_models
from reviews import forms as review_forms
from . import models as reservation_models


class CreateError(Exception):
    """ Exception Error class """

    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        reservation_models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError("이미 예약되어 있어요")

    except room_models.Room.DoesNotExist:
        messages.error(request, "이 숙소는 예약할 수 없습니다😰")
        return redirect(reverse("core:home"))

    except CreateError as error_context:
        messages.error(request, error_context)
        return redirect(reverse("core:home"))

    except reservation_models.BookedDay.DoesNotExist:
        reservation = reservation_models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationDetailView(View):
    """ View of Reservation Detail """

    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = reservation_models.Reservation.objects.get_or_none(pk=pk)
        is_guest = reservation.guest == self.request.user
        is_host = reservation.room.host == self.request.user

        if not reservation or (not is_host and not is_guest):
            raise Http404()

        form = review_forms.CreateReviewForm()

        return render(
            self.request,
            "reservations/reservation_detail.html",
            {"reservation": reservation, "form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = reservation_models.Reservation.objects.get_or_none(pk=pk)
    is_guest = reservation.guest == request.user
    is_host = reservation.room.host == request.user

    if not reservation or (not is_host and not is_guest):
        raise Http404()

    if verb == "confirm":
        reservation.status = reservation_models.Reservation.STATUS_CONFIRMED
        # Todo

    elif verb == "cancel":
        reservation.status = reservation_models.Reservation.STATUS_CANCELED
        reservation_models.BookedDay.objects.filter(reservation=reservation).delete()

    reservation.save()
    messages.success(request, "예약 내용이 변경되었습니다")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class ReservationListView(ListView):

    """ ReservationListView Definition """

    model = reservation_models.Reservation
    paginate_by = 12
    paginate_orphans = 5
    ordering = "-check_in"

templates/reservations/detail.html
{% extends "base.html" %}

{% block page_title %}
  예약 {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
  <div class="container mx-auto mt-32 mb-10 flex flex-col">

    <div class="p-4 mb-4 border-b border-gray-300 flex justify-between items-center">
      <a href="{% url 'rooms:detail' reservation.room.pk %}" class="text-blue-500 font-medium">
        <i class="fas fa-arrow-left"></i>
        <span>숙소 보기</span>
      </a>
    </div>

    <div class="bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.get_first_photo}});"></div>
    
    <div class="flex flex-col items-start border-l border-r border-b">
      <div class="py-6 px-4 border-b w-full font-medium">
        <span>{{reservation.check_in}} - {{reservation.check_out}}</span>
        <span class="ml-4 font-semibold {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{reservation.get_status_display}}</span>
      </div>
  
      <div class="text-2xl px-4 py-6 font-medium border-b w-full">
        {{reservation.room.name}}
      </div>
  
      <div class="flex py-10 px-4 {% if reservation.status != 'canceled' %} border-b {% endif %} w-full">
        <a href="{{reservation.room.host.get_absolute_url}}" class="flex flex-col items-center">
          {% include "mixins/user_avatar.html" with user=reservation.room.host %}
          <span class="mt-1 font-medium text-gray-500">{{reservation.room.host.first_name}}</span>
        </a>
        <div class="ml-6 flex flex-col">
          <span class="font-medium mb-2 text-lg">Contact your Bongnb Host</span>
          <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="text-teal-500 font-semibold">Send a Message</a>
        </div>
      </div>
  
      
      {% if reservation.status != 'canceled' %}
        <div class="py-10 px-4 flex flex-col w-full">
          {% if reservation.status == 'confirmed' and reservation.is_finished %}
            <span class="font-semibold text-2xl text-center block w-full mb-4">이 숙소는 어땠나요?</span>
            <form action="{% url 'reviews:create' room=reservation.room.pk %}" method="post"
            class="w-full md:w-1/2 mx-auto"
            >
              {% csrf_token %}
              {{form}}
              <button class="btn mt-10 bg-indigo-500 text-white">리뷰 작성</button>
            </form>
          
          {% else %}

            {% if reservation.status == 'pending' %}
              <a
              href="{% url 'reservations:edit' reservation.pk 'cancel' %}"
              class="btn-link px-10 bg-red-500 text-base py-4"
              >Cancel Reservation</a>
              {% if reservation.room.host == user %}
                <a
                href="{% url 'reservations:edit' reservation.pk 'confirm' %}"
                class="btn-link px-10 bg-blue-500 text-base mt-4 py-4"
                >Confirm Reservation</a>
              {% endif %}
            {% endif %}
          {% endif %}
        </div>
      {% endif %}
          
    </div>
    

  </div>

{% endblock content %}

templates/reservations/reservation_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{reservation.check_in|date:"Y년 n월 d일"}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
  <div class="container mx-auto mt-32 mb-10 flex flex-col">

    <div class="bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.get_first_photo}});"></div>
    
    <div class="flex flex-col items-start border-l border-r border-b">
      <div class="py-6 px-4 border-b w-full font-medium">
        <span>{{reservation.check_in|date:"Y년 n월 d일"}}</span>
        <span>-</span>
        <span>{{reservation.check_out|date:"Y년 n월 d일"}}</span>
        <span class="ml-4 font-semibold
          {% if reservation.status == 'pending' %} text-orange-500
          {% elif reservation.status == 'canceled' %} text-red-600
          {% else %} text-blue-600
          {% endif %}">{{reservation.get_status_display}}</span>
      </div>
  
      <a href="{% url 'rooms:detail' reservation.room.pk %}" class="text-2xl px-4 py-6 font-medium border-b w-full">
        {{reservation.room.name}}
      </a>
  
      <div class="flex py-10 px-4 {% if reservation.status != 'canceled' %} border-b {% endif %} w-full">
        <a href="{{reservation.room.host.get_absolute_url}}" class="flex flex-col items-center">
          {% include "mixins/user_avatar.html" with user=reservation.room.host %}
          <span class="mt-1 font-medium text-gray-500">{{reservation.room.host.first_name}}</span>
        </a>
        <div class="ml-6 flex flex-col">
          <span class="font-medium mb-2 text-lg">Contact your Bongnb Host</span>
          <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="text-teal-500 font-semibold">Send a Message</a>
        </div>
      </div>
  
      
      {% if reservation.status != 'canceled' %}
        <div class="py-10 px-4 flex flex-col w-full">
          {% if reservation.status == 'confirmed' and reservation.is_finished %}
            <span class="font-semibold text-2xl text-center block w-full mb-4">이 숙소는 어땠나요?</span>
            <form action="{% url 'reviews:create' room=reservation.room.pk %}" method="post"
            class="w-full md:w-1/2 mx-auto"
            >
              {% csrf_token %}
              {{form}}
              <button class="btn mt-10 bg-indigo-500 text-white">리뷰 작성</button>
            </form>
          
          {% else %}

            {% if reservation.status == 'pending' %}
              <a
              href="{% url 'reservations:edit' reservation.pk 'cancel' %}"
              class="btn-link px-10 bg-red-500 text-base py-4"
              >Cancel Reservation</a>
              {% if reservation.room.host == user %}
                <a
                href="{% url 'reservations:edit' reservation.pk 'confirm' %}"
                class="btn-link px-10 bg-blue-500 text-base mt-4 py-4"
                >Confirm Reservation</a>
              {% endif %}
            {% endif %}
          {% endif %}
        </div>
      {% endif %}
          
    </div>
    

  </div>

{% endblock content %}

templates/reservations/reservation_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}
    home
{% endblock page_title %}

{% block content %}

    <div class="min-h-75vh container container-m-p mb-10">

        <p class="w-full font-semibold text-xl mb-10">예약목록</p>

        <div class="flex flex-wrap mb-10 sm:-mx-2">
            {% for reservation in object_list %}
                {% include "mixins/room_reservation.html" with reservation=reservation %}
            {% empty %}
                <p>예약한 숙소가 없어요.</p>
            {% endfor %}
        </div>
        
        {% if object_list.count != 0 %}
            
            <div class="flex items-center flex-col justify-center">
                <div>
                    {% if page_obj.has_previous %}
                        <a
                            href="?page={{page_obj.previous_page_number}}"
                            class="flex items-center justify-center w-8 h-8 rounded-full border border-gray-300
                            transition-shadow shadow-md hover:shadow-lg duration-200 ease-in-out
                        ">
                            <i class="fas fa-chevron-left"></i>
                        </a>
                    {% endif %}
                    
                    <span class="mx-2 font-medium">
                        
                        {% blocktrans with cp=page_obj.number tp=page_obj.paginator.num_pages %}page {{cp}} of {{tp}}{% endblocktrans %}
                        
                    </span>
        
                    {% if page_obj.has_next %}
                        <a
                            href="?page={{page_obj.next_page_number}}"
                            class="flex items-center justify-center w-8 h-8 rounded-full border border-gray-300
                                transition-shadow shadow-md hover:shadow-lg duration-200 ease-in-out
                        ">
                            <i class="fas fa-chevron-right"></i>
                        </a>        
                    {% endif %}
                </div>
            </div>

        {% endif %}
            
    </div>

{% endblock content %}